/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

package me.him188.ani.datasources.bangumi.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * - `1`: 想看 - `2`: 看过 - `3`: 在看 - `4`: 搁置 - `5`: 抛弃
 *
 * Values: Wish,Done,Doing,OnHold,Dropped
 */
@Serializable(AsInt::class)
enum class BangumiSubjectCollectionType(val value: Int) {

    @SerialName(value = "1")
    Wish(1),

    @SerialName(value = "2")
    Done(2),

    @SerialName(value = "3")
    Doing(3),

    @SerialName(value = "4")
    OnHold(4),

    @SerialName(value = "5")
    Dropped(5);

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value.toString()
}

private object AsInt : EnumValueSerializer<BangumiSubjectCollectionType>(
    "BangumiSubjectCollectionType", BangumiSubjectCollectionType.entries, { it.value },
)
