/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package me.him188.ani.app.torrent.anitorrent.binding;

public class anitorrent {
    public static SWIGTYPE_p_libtorrent__session new_session(String user_agent) {
        long cPtr = anitorrentJNI.new_session(user_agent);
        return (cPtr == 0) ? null : new SWIGTYPE_p_libtorrent__session(cPtr, false);
    }

    public static String fetch_magnet(SWIGTYPE_p_libtorrent__session s, String uri, int timeout_seconds, String save_path) {
        return anitorrentJNI.fetch_magnet(SWIGTYPE_p_libtorrent__session.getCPtr(s), uri, timeout_seconds, save_path);
    }

}
