/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package me.him188.ani.app.torrent.anitorrent.binding;

public class anitorrentJNI {
    public final static native long new_stats();

    public final static native void delete_stats(long jarg1);

    public final static native long new_session(String jarg1);

    public final static native String fetch_magnet(long jarg1, String jarg2, int jarg3, String jarg4);
}
