/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package me.him188.ani.app.torrent.anitorrent.binding;

public class SWIGTYPE_p_libtorrent__session {
    private transient long swigCPtr;

    protected SWIGTYPE_p_libtorrent__session(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
        swigCPtr = cPtr;
    }

    protected SWIGTYPE_p_libtorrent__session() {
        swigCPtr = 0;
    }

    protected static long getCPtr(SWIGTYPE_p_libtorrent__session obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }

    protected static long swigRelease(SWIGTYPE_p_libtorrent__session obj) {
        return (obj == null) ? 0 : obj.swigCPtr;
    }
}

