/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


#define SWIG_VERSION 0x040201
#define SWIGJAVA

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif

#if defined(__cplusplus) && __cplusplus >= 201103L
# define SWIG_NULLPTR nullptr
#else
# define SWIG_NULLPTR NULL
#endif

/* -----------------------------------------------------------------------------
 * swigcompat.swg
 *
 * Macros to provide support compatibility with older C and C++ standards.
 * ----------------------------------------------------------------------------- */

/* C99 and C++11 should provide snprintf, but define SWIG_NO_SNPRINTF
 * if you're missing it.
 */
#if ((defined __STDC_VERSION__ && __STDC_VERSION__ >= 199901L) || \
     (defined __cplusplus && __cplusplus >= 201103L) || \
     defined SWIG_HAVE_SNPRINTF) && \
    !defined SWIG_NO_SNPRINTF
# define SWIG_snprintf(O,S,F,A) snprintf(O,S,F,A)
# define SWIG_snprintf2(O,S,F,A,B) snprintf(O,S,F,A,B)
#else
/* Fallback versions ignore the buffer size, but most of our uses either have a
 * fixed maximum possible size or dynamically allocate a buffer that's large
 * enough.
 */
# define SWIG_snprintf(O, S, F, A) sprintf(O,F,A)
# define SWIG_snprintf2(O, S, F, A, B) sprintf(O,F,A,B)
#endif


#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
    SWIG_JavaOutOfMemoryError = 1,
    SWIG_JavaIOException,
    SWIG_JavaRuntimeException,
    SWIG_JavaIndexOutOfBoundsException,
    SWIG_JavaArithmeticException,
    SWIG_JavaIllegalArgumentException,
    SWIG_JavaNullPointerException,
    SWIG_JavaDirectorPureVirtual,
    SWIG_JavaUnknownError,
    SWIG_JavaIllegalStateException,
} SWIG_JavaExceptionCodes;

typedef struct {
    SWIG_JavaExceptionCodes code;
    const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED
SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
    jclass excep;
    static const SWIG_JavaExceptions_t java_exceptions[] = {
            {SWIG_JavaOutOfMemoryError,          "java/lang/OutOfMemoryError"},
            {SWIG_JavaIOException,               "java/io/IOException"},
            {SWIG_JavaRuntimeException,          "java/lang/RuntimeException"},
            {SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException"},
            {SWIG_JavaArithmeticException,       "java/lang/ArithmeticException"},
            {SWIG_JavaIllegalArgumentException,  "java/lang/IllegalArgumentException"},
            {SWIG_JavaNullPointerException,      "java/lang/NullPointerException"},
            {SWIG_JavaDirectorPureVirtual,       "java/lang/RuntimeException"},
            {SWIG_JavaUnknownError,              "java/lang/UnknownError"},
            {SWIG_JavaIllegalStateException,     "java/lang/IllegalStateException"},
            {(SWIG_JavaExceptionCodes) 0,        "java/lang/UnknownError"}
    };
    const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

    while (except_ptr->code != code && except_ptr->code)
        except_ptr++;

    jenv->ExceptionClear();
    excep = jenv->FindClass(except_ptr->java_exception);
    if (excep)
        jenv->ThrowNew(excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) do { if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } } while (0)


#ifdef __cplusplus
#include <utility>
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigSmartPointer {
    T *ptr;
    SwigSmartPointer(T *p) : ptr(p) { }
    ~SwigSmartPointer() { delete ptr; }
    SwigSmartPointer& operator=(SwigSmartPointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
    void reset(T *p) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = p; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigSmartPointer tmp(new T(t)); pointer = tmp; return *this; }
#if __cplusplus >=201103L
  SwigValueWrapper& operator=(T&& t) { SwigSmartPointer tmp(new T(std::move(t))); pointer = tmp; return *this; }
  operator T&&() const { return std::move(*pointer.ptr); }
#else
  operator T&() const { return *pointer.ptr; }
#endif
  T *operator&() const { return pointer.ptr; }
  static void reset(SwigValueWrapper& t, T *p) { t.pointer.reset(p); }
};

/*
 * SwigValueInit() is a generic initialisation solution as the following approach:
 * 
 *       T c_result = T();
 * 
 * doesn't compile for all types for example:
 * 
 *       unsigned int c_result = unsigned int();
 */
template <typename T> T SwigValueInit() {
  return T();
}

#if __cplusplus >=201103L
# define SWIG_STD_MOVE(OBJ) std::move(OBJ)
#else
# define SWIG_STD_MOVE(OBJ) OBJ
#endif

#endif


#include "anitorrent.h"


#include <string>


#include <typeinfo>
#include <stdexcept>


#include <vector>
#include <stdexcept>


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jlong JNICALL
Java_me_him188_ani_app_torrent_anitorrent_binding_anitorrentJNI_new_1stats(JNIEnv
*jenv,
jclass jcls
) {
jlong jresult = 0;
anilt::session::stats *result = 0;

(void)
jenv;
(void)
jcls;
result = (anilt::session::stats *) new anilt::session::stats();
*(anilt::session::stats **)&
jresult = result;
return
jresult;
}


SWIGEXPORT void JNICALL
Java_me_him188_ani_app_torrent_anitorrent_binding_anitorrentJNI_delete_1stats(JNIEnv
*jenv,
jclass jcls, jlong
jarg1) {
anilt::session::stats *arg1 = (anilt::session::stats *) 0;

(void)
jenv;
(void)
jcls;
arg1 = *(anilt::session::stats **) &jarg1;
delete
arg1;
}


SWIGEXPORT jlong JNICALL
Java_me_him188_ani_app_torrent_anitorrent_binding_anitorrentJNI_new_1session(JNIEnv
*jenv,
jclass jcls, jstring
jarg1) {
jlong jresult = 0;
char *arg1 = (char *) 0;
libtorrent::session *result = 0;

(void)
jenv;
(void)
jcls;
arg1 = 0;
if (jarg1) {
arg1 = (char *) jenv->GetStringUTFChars(jarg1, 0);
if (!arg1) return 0;
}
result = (libtorrent::session *) anilt::session::new_session((char const *) arg1);
*(libtorrent::session **)&
jresult = result;
if (arg1) jenv->
ReleaseStringUTFChars(jarg1,
(const char *)arg1);
return
jresult;
}


SWIGEXPORT jstring JNICALL
Java_me_him188_ani_app_torrent_anitorrent_binding_anitorrentJNI_fetch_1magnet(JNIEnv
*jenv,
jclass jcls, jlong
jarg1,
jstring jarg2, jint
jarg3,
jstring jarg4
) {
jstring jresult = 0;
libtorrent::session *arg1 = (libtorrent::session *) 0;
std::string *arg2 = 0;
int arg3;
std::string *arg4 = 0;
std::string result;

(void)
jenv;
(void)
jcls;
arg1 = *(libtorrent::session **) &jarg1;
if(!jarg2) {
SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException,
"null string");
return 0;
}
const char *arg2_pstr = (const char *) jenv->GetStringUTFChars(jarg2, 0);
if (!arg2_pstr) return 0;
std::string arg2_str(arg2_pstr);
arg2 = &arg2_str;
jenv->
ReleaseStringUTFChars(jarg2, arg2_pstr
);
arg3 = (int) jarg3;
if(!jarg4) {
SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException,
"null string");
return 0;
}
const char *arg4_pstr = (const char *) jenv->GetStringUTFChars(jarg4, 0);
if (!arg4_pstr) return 0;
std::string arg4_str(arg4_pstr);
arg4 = &arg4_str;
jenv->
ReleaseStringUTFChars(jarg4, arg4_pstr
);
result = anilt::session::fetch_magnet(arg1, (std::string const &) *arg2, arg3,
                                      (std::string const &) *arg4);
jresult = jenv->NewStringUTF((&result)->c_str());
return
jresult;
}


#ifdef __cplusplus
}
#endif

